#!/usr/bin/env python3
"""Cross-platform installer and launcher for AI Platform."""

from __future__ import annotations

import argparse
import getpass
import json
import os
from pathlib import Path
import secrets
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
ENV_FILE = BACKEND / ".env"
REQUIREMENTS = BACKEND / "requirements.txt"
VENV = ROOT / ".venv"
MIN_PYTHON = (3, 11)


def venv_python() -> Path:
    if os.name == "nt":
        return VENV / "Scripts" / "python.exe"
    return VENV / "bin" / "python"


def read_env(path: Path = ENV_FILE) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value.startswith(('"', "'")) and value.endswith(value[:1]):
            if value.startswith('"'):
                try:
                    value = json.loads(value)
                except json.JSONDecodeError:
                    value = value[1:-1]
            else:
                value = value[1:-1]
        values[key] = value
    return values


def env_value(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def write_env(values: dict[str, str], path: Path = ENV_FILE) -> None:
    sections = [
        ("Core runtime", [
            "ENVIRONMENT", "BACKEND_HOST", "BACKEND_PORT", "PUBLIC_BASE_URL",
            "PROJECT_ROOT", "DATABASE_URL", "REDIS_URL", "AUTO_CREATE_DB_TABLES",
            "SECRET_KEY", "AUTH_TOKEN_SECRET",
        ]),
        ("AI providers", [
            "OPENAI_API_KEY", "OPENAI_BASE_URL", "ROUTERAI_API_KEY",
            "ROUTERAI_BASE_URL", "RUAPI_API_KEY", "RUAPI_BASE_URL",
            "CLAUDEHUB_API_KEY", "CLAUDEHUB_BASE_URL", "ANTHROPIC_API_KEY",
            "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_BASE_URL", "GOOGLE_API_KEY",
            "GEMINI_API_KEY",
        ]),
        ("Optional integrations", [
            "YOOKASSA_SHOP_ID", "YOOKASSA_SECRET_KEY", "YOOKASSA_RETURN_URL",
            "YOOKASSA_WEBHOOK_SECRET", "SMTP_HOST", "SMTP_PORT", "SMTP_USERNAME",
            "SMTP_PASSWORD", "SMTP_FROM_EMAIL", "SMTP_FROM_NAME", "SMTP_USE_TLS",
        ]),
    ]
    lines = ["# Generated by scripts/ai_platform.py. Do not commit this file."]
    written: set[str] = set()
    for title, keys in sections:
        lines.extend(["", f"# {title}"])
        for key in keys:
            if key in values:
                lines.append(f"{key}={env_value(values[key])}")
                written.add(key)
    for key in sorted(set(values) - written):
        lines.append(f"{key}={env_value(values[key])}")

    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as handle:
        handle.write("\n".join(lines) + "\n")
        temp_path = Path(handle.name)
    temp_path.replace(path)
    if os.name != "nt":
        path.chmod(0o600)


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    answer = input(f"{label}{suffix}: ").strip()
    return answer or default


def default_config(existing: dict[str, str] | None = None) -> dict[str, str]:
    values = dict(existing or {})
    values.setdefault("ENVIRONMENT", "development")
    values.setdefault("BACKEND_HOST", "127.0.0.1")
    values.setdefault("BACKEND_PORT", "8000")
    values.setdefault("PUBLIC_BASE_URL", "http://127.0.0.1:8000")
    values["PROJECT_ROOT"] = str(ROOT)
    values.setdefault("DATABASE_URL", "sqlite:///./ai_workspace.db")
    values.setdefault("REDIS_URL", "redis://127.0.0.1:6379/0")
    values.setdefault("AUTO_CREATE_DB_TABLES", "true")
    values.setdefault("SECRET_KEY", secrets.token_urlsafe(48))
    values.setdefault("AUTH_TOKEN_SECRET", secrets.token_urlsafe(48))
    return values


PROVIDERS = {
    "none": (None, None),
    "openai": ("OPENAI_API_KEY", "OPENAI_BASE_URL"),
    "routerai": ("ROUTERAI_API_KEY", "ROUTERAI_BASE_URL"),
    "ruapi": ("RUAPI_API_KEY", "RUAPI_BASE_URL"),
    "claudehub": ("CLAUDEHUB_API_KEY", "CLAUDEHUB_BASE_URL"),
    "anthropic": ("ANTHROPIC_API_KEY", "ANTHROPIC_BASE_URL"),
    "google": ("GOOGLE_API_KEY", None),
}


def configure(args: argparse.Namespace) -> dict[str, str]:
    existing = read_env()
    values = default_config(existing)
    if args.yes:
        host, port, provider = args.host, str(args.port), args.provider
    else:
        print("\nAI Platform configuration")
        host = prompt("Bind address", values["BACKEND_HOST"])
        port = prompt("Port", values["BACKEND_PORT"])
        print("Providers: none, openai, routerai, ruapi, claudehub, anthropic, google")
        provider = prompt("Provider", args.provider).lower()
    if provider not in PROVIDERS:
        raise SystemExit(f"Unknown provider: {provider}")
    try:
        parsed_port = int(port)
        if not 1 <= parsed_port <= 65535:
            raise ValueError
    except ValueError as exc:
        raise SystemExit("Port must be an integer from 1 to 65535") from exc

    values["BACKEND_HOST"] = host
    values["BACKEND_PORT"] = str(parsed_port)
    public_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    values["PUBLIC_BASE_URL"] = f"http://{public_host}:{parsed_port}"

    key_name, base_name = PROVIDERS[provider]
    if key_name:
        current_key = values.get(key_name, "")
        if args.yes:
            api_key = current_key
        else:
            marker = " (already configured)" if current_key else ""
            api_key = getpass.getpass(f"{key_name}{marker}: ").strip() or current_key
        if api_key:
            values[key_name] = api_key
    if base_name:
        default_url = values.get(base_name, "")
        if provider == "openai" and not default_url:
            default_url = "https://api.openai.com/v1"
        values[base_name] = default_url if args.yes else prompt(base_name, default_url)
    return values


def install_dependencies() -> None:
    if not VENV.exists():
        print(f"Creating virtual environment: {VENV}")
        subprocess.run([sys.executable, "-m", "venv", str(VENV)], check=True)
    python = venv_python()
    subprocess.run([str(python), "-m", "pip", "install", "--upgrade", "pip"], check=True)
    subprocess.run([str(python), "-m", "pip", "install", "-r", str(REQUIREMENTS)], check=True)


def command_setup(args: argparse.Namespace) -> int:
    if sys.version_info < MIN_PYTHON:
        raise SystemExit("AI Platform requires Python 3.11 or newer")
    if ENV_FILE.exists() and not args.force and not args.yes:
        answer = prompt("backend/.env exists. Update it?", "no").lower()
        if answer not in {"y", "yes", "да", "д"}:
            print("Configuration kept unchanged.")
            return 0
    values = configure(args)
    write_env(values)
    print(f"Configuration written to {ENV_FILE}")
    if not args.skip_install:
        install_dependencies()
    print("\nInstallation complete.")
    print(f"Start: {venv_python()} {ROOT / 'scripts' / 'ai_platform.py'} run")
    print(f"Open:  {values['PUBLIC_BASE_URL']}/chat")
    return 0


def command_check(_args: argparse.Namespace) -> int:
    checks = {
        "Python 3.11+": sys.version_info >= MIN_PYTHON,
        "backend/requirements.txt": REQUIREMENTS.is_file(),
        "backend/.env": ENV_FILE.is_file(),
        "virtual environment": venv_python().is_file(),
    }
    values = read_env()
    checks["SECRET_KEY configured"] = len(values.get("SECRET_KEY", "")) >= 32
    checks["AUTH_TOKEN_SECRET configured"] = len(values.get("AUTH_TOKEN_SECRET", "")) >= 32
    for label, passed in checks.items():
        print(f"{'OK' if passed else 'FAIL':4}  {label}")
    if not all(checks.values()):
        return 1
    result = subprocess.run(
        [str(venv_python()), "-c", "import app.main"],
        cwd=BACKEND,
        text=True,
        capture_output=True,
    )
    if result.returncode:
        print("FAIL  backend import")
        if result.stderr:
            print(result.stderr.strip())
        return 1
    print("OK    backend import")
    return 0


def command_run(args: argparse.Namespace) -> int:
    if not venv_python().is_file() or not ENV_FILE.is_file():
        print("AI Platform is not configured. Run setup first.", file=sys.stderr)
        return 1
    values = read_env()
    host = args.host or values.get("BACKEND_HOST", "127.0.0.1")
    port = args.port or int(values.get("BACKEND_PORT", "8000"))
    command = [
        str(venv_python()), "-m", "uvicorn", "app.main:app",
        "--host", host, "--port", str(port),
    ]
    if args.reload:
        command.append("--reload")
    return subprocess.run(command, cwd=BACKEND).returncode


def command_status(_args: argparse.Namespace) -> int:
    values = read_env()
    url = values.get("PUBLIC_BASE_URL", "http://127.0.0.1:8000").rstrip("/") + "/health"
    try:
        with urllib.request.urlopen(url, timeout=3) as response:
            payload = response.read().decode("utf-8")
        print(f"Running: {url}\n{payload}")
        return 0
    except (urllib.error.URLError, TimeoutError) as exc:
        print(f"Not reachable: {url} ({exc})")
        return 1


def systemd_unit() -> str:
    python = venv_python()
    launcher = ROOT / "scripts" / "ai_platform.py"
    return f"""[Unit]
Description=AI Platform
After=network-online.target

[Service]
Type=simple
WorkingDirectory={BACKEND}
ExecStart={python} {launcher} run
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


def command_service_install(_args: argparse.Namespace) -> int:
    if not sys.platform.startswith("linux"):
        print("Automatic service installation currently supports Linux/systemd only.")
        return 1
    if not venv_python().is_file() or not ENV_FILE.is_file():
        print("Run setup before installing the service.", file=sys.stderr)
        return 1
    target = Path.home() / ".config" / "systemd" / "user" / "ai-platform.service"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(systemd_unit(), encoding="utf-8")
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "--user", "enable", "--now", "ai-platform.service"], check=True)
    print(f"Service installed: {target}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Install and run AI Platform")
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup = subparsers.add_parser("setup", help="create config and install dependencies")
    setup.add_argument("--yes", action="store_true", help="use non-interactive defaults")
    setup.add_argument("--force", action="store_true", help="replace/update existing config")
    setup.add_argument("--skip-install", action="store_true", help="do not create the virtualenv")
    setup.add_argument("--host", default="127.0.0.1")
    setup.add_argument("--port", type=int, default=8000)
    setup.add_argument("--provider", choices=sorted(PROVIDERS), default="none")
    setup.set_defaults(func=command_setup)

    run = subparsers.add_parser("run", help="start the web application")
    run.add_argument("--host")
    run.add_argument("--port", type=int)
    run.add_argument("--reload", action="store_true")
    run.set_defaults(func=command_run)

    check = subparsers.add_parser("check", help="validate the installation")
    check.set_defaults(func=command_check)
    status = subparsers.add_parser("status", help="check the running server")
    status.set_defaults(func=command_status)
    service = subparsers.add_parser("service-install", help="install a Linux user service")
    service.set_defaults(func=command_service_install)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
