from __future__ import annotations

from pathlib import Path
from urllib.parse import urlsplit, urlunsplit


ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT / "backend"
TARGET = BACKEND_DIR / ".env.postgres.rehearsal"
TEMPLATE = BACKEND_DIR / ".env.postgres.rehearsal.example"
PRIMARY_ENV = BACKEND_DIR / ".env"
ENV_EXAMPLE = BACKEND_DIR / ".env.example"

SECTIONS = [
    (
        "Core runtime",
        [
            "ENVIRONMENT",
            "AUTO_CREATE_DB_TABLES",
            "BACKEND_HOST",
            "BACKEND_PORT",
            "PUBLIC_BASE_URL",
        ],
    ),
    ("Database and cache", ["DATABASE_URL", "REDIS_URL"]),
    ("Auth", ["AUTH_TOKEN_SECRET", "SECRET_KEY", "AUTH_TOKEN_TTL_SECONDS"]),
    (
        "AI gateway",
        [
            "RUAPI_API_KEY",
            "RUAPI_BASE_URL",
            "OPENAI_API_KEY",
            "OPENAI_BASE_URL",
            "CLAUDEHUB_API_KEY",
            "CLAUDEHUB_BASE_URL",
            "ROUTERAI_API_KEY",
            "ROUTERAI_BASE_URL",
            "ANTHROPIC_API_KEY",
            "ANTHROPIC_AUTH_TOKEN",
            "ANTHROPIC_BASE_URL",
            "GOOGLE_API_KEY",
            "GEMINI_API_KEY",
        ],
    ),
    ("Billing", ["YOOKASSA_SHOP_ID", "YOOKASSA_SECRET_KEY", "YOOKASSA_RETURN_URL"]),
    (
        "SMTP",
        [
            "SMTP_HOST",
            "SMTP_PORT",
            "SMTP_USERNAME",
            "SMTP_PASSWORD",
            "SMTP_FROM_EMAIL",
            "SMTP_FROM_NAME",
            "SMTP_USE_TLS",
        ],
    ),
]


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def derive_rehearsal_database_url(value: str) -> str:
    if not value.startswith(("postgresql://", "postgresql+psycopg://")):
        return value

    parsed = urlsplit(value)
    current_path = parsed.path or ""
    db_name = current_path.rsplit("/", 1)[-1] if "/" in current_path else current_path.lstrip("/")
    if not db_name:
        db_name = "ai_workspace"
    if not db_name.endswith("_rehearsal"):
        db_name = f"{db_name}_rehearsal"
    new_path = "/" + db_name
    return urlunsplit((parsed.scheme, parsed.netloc, new_path, parsed.query, parsed.fragment))


def build_rehearsal_values() -> dict[str, str]:
    template_values = parse_env_file(TEMPLATE)
    example_values = parse_env_file(ENV_EXAMPLE)
    primary_values = parse_env_file(PRIMARY_ENV)
    merged = dict(template_values)

    for key, value in example_values.items():
        merged.setdefault(key, value)

    for key, value in primary_values.items():
        if value:
            merged[key] = value

    merged["ENVIRONMENT"] = "production"
    merged["AUTO_CREATE_DB_TABLES"] = "false"
    merged["PUBLIC_BASE_URL"] = merged.get("PUBLIC_BASE_URL") or "http://127.0.0.1:8000"
    merged["BACKEND_HOST"] = merged.get("BACKEND_HOST") or "0.0.0.0"
    merged["BACKEND_PORT"] = merged.get("BACKEND_PORT") or "8000"
    merged["DATABASE_URL"] = derive_rehearsal_database_url(
        merged.get("DATABASE_URL")
        or "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/ai_workspace_rehearsal"
    )
    merged["REDIS_URL"] = merged.get("REDIS_URL") or "redis://127.0.0.1:6379/0"
    merged["YOOKASSA_RETURN_URL"] = merged.get("YOOKASSA_RETURN_URL") or f"{merged['PUBLIC_BASE_URL'].rstrip('/')}/chat"
    merged["SMTP_PORT"] = merged.get("SMTP_PORT") or "587"
    merged["SMTP_FROM_NAME"] = merged.get("SMTP_FROM_NAME") or "AI Workspace Platform"
    merged["SMTP_USE_TLS"] = merged.get("SMTP_USE_TLS") or "true"
    merged.setdefault("AUTH_TOKEN_TTL_SECONDS", "2592000")

    return merged


def render_env(values: dict[str, str]) -> str:
    lines = [
        "# PostgreSQL rehearsal environment",
        "# Generated by scripts/prepare_postgres_rehearsal_env.py",
        "# Replace placeholder secrets before running scripts/postgres_rehearsal_runner.sh.",
        "",
    ]
    for title, keys in SECTIONS:
        lines.append(f"# {title}")
        for key in keys:
            lines.append(f"{key}={values.get(key, '')}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    if TARGET.exists():
        print(f"Rehearsal env already exists: {TARGET}")
        return
    if not TEMPLATE.exists():
        raise SystemExit(f"Missing template: {TEMPLATE}")

    values = build_rehearsal_values()
    TARGET.write_text(render_env(values), encoding="utf-8")
    print(f"Created rehearsal env from template and current config: {TARGET}")
    print("Next: replace placeholder secrets and verify DATABASE_URL points to a real rehearsal database.")


if __name__ == "__main__":
    main()
